url: "https://ieee-sb-naist.github.io/"
baseurl: ""

# Site settings
title: IEEE SB NAIST
email: sb.naist@ieee.org
description: "Official Website of the IEEE NAIST Student Branch"


# Team names, titles and social links
people:
- name: Yohanssen Pratama
  pic: yohanssen-p
  position: Chair

- name: Ndalama Festus Edward
  pic: ndalama-f-e
  position: Vice Chair
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/festus-ndalama-50896356/

- name: Indira Febriyanti
  pic: indira-f
  position: Secretary
  social:
    - title: github
      url: https://github.com/Indirafyn/

- name: Valerie Megan
  pic: ieee-sb-naist
  position: Treasurer

- name: Sergio De Leon
  pic: sergio-dl
  position: Webmaster
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sergio-de-leon-2011/
    - title: github
      url: https://github.com/sergiodltech/

- name: Olufemi Abraham
  pic: olufemi
  position: Member
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/olufemi-abraham-86b0b433/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ieee.sb.naist
  - title: twitter
    url: https://twitter.com/ieee_sb_naist
  - title: instagram
    url: https://www.instagram.com/ieee_sb_naist/

# Postal address (add as many lines as necessary)
address:
  - line: Nara Institute of Science and Technology (NAIST), 8916-5 Takayama-cho, Ikoma
  - line: Nara, Japan, 630-0192

# Build settings
markdown: kramdown
permalink: pretty
