url: "https://ieee-sb-naist.github.io/"
baseurl: ""

# Site settings
title: IEEE SB NAIST
email: sb.naist@ieee.org
description: "Official Website of the IEEE NAIST Student Branch"


# Team names, titles and social links
people:
- name: Olufemi Abraham
  pic: olufemi
  position: Chair
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/olufemi-abraham-86b0b433/
  
- name: Thuwiba Ibrahim
  position: Vice Chair

- name: Sergio De Leon Aguilar
  position: Secretary

- name: Yohanssen Pratama
  position: Treasurer

- name: Kang Xingyuan
  position: Webmaster
  
- name: Andres Gomez
  pic: andres
  position: Member
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/andresrobertogomez/

- name: Mario Aburto
  pic: mario_new
  position: Member
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mario-eduardo-aburto-guti%C3%A9rrez-19b233129/
    - title: github
      url: https://github.com/maburto00
    - title: globe
      url: https://maburto00.github.io/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ieee.sb.naist
  - title: twitter
    url: https://twitter.com/ieee_sb_naist
  - title: instagram
    url: https://www.instagram.com/ieee_sb_naist/

# Postal address (add as many lines as necessary)
address:
  - line: Nara Institute of Science and Technology (NAIST), 8916-5 Takayama-cho, Ikoma
  - line: Nara, Japan, 630-0192

# Build settings
markdown: kramdown
permalink: pretty
