url: https://rizarae-p.github.io/
baseurl: /ieee-sb-naist

# Site settings
title: IEEE SB NAIST
email: your-email@domain.com
description: "Official Website of the IEEE NAIST Student Branch"


# Team names, titles and social links
people:
- name: Niu Zhaofeng
  pic: 1
  position: President
  social:
    

- name: Mutinda Faith Wavinya
  pic: 2
  position: Vice President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Riza Rae Pineda
  pic: 3
  position: Secretary
  social:
    - title: linkedin
      url: https://ph.linkedin.com/in/riza-rae-pineda-b3671263
    - title: github
      url: https://github.com/rizarae-p
    - title: instagram
      url: https://www.instagram.com/rizarae/

- name: Mario Aburto
  pic: 3
  position: Treasurer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/NaistSb
  - title: facebook
    url: https://www.facebook.com/IEEE-NAIST-Student-Branch-101517378336895

# Postal address (add as many lines as necessary)
address:
  - line: Nara Institute of Science and Technology (NAIST), 8916-5 Takayama-cho, Ikoma
  - line: Nara, Japan, 630-0192

# Build settings
markdown: kramdown
permalink: pretty